### ISSUE TITLE
Connection to pimatic failed

### ISSUE THREAD

**Issue by lxz81** [Okadesde/esp8266-pimatic-Arduino#1]
so far, i have succesfully got the web interface and temperture sensor working. But unfortunately I am not able to connect to the pimatic instance. 

In your code i see some ip adresses which are static. I tried to change these to my own, but still no luck. 

Can you take a look and help me out?

**Comment by renearts** [comment]
I'm having this issue as well, also mentioned on the pimatic forum.

**Comment by renearts** [comment]
I pushed some fixes which just got merged, connecting to pimatic should be working now :)

**Comment by lxz81** [comment]
Hey thanks for fixing. Is working now!
